### ISSUE TITLE
Import Trace for requested Module

### ISSUE THREAD

**Issue by ThaMacroMan** [MartifyLabs/starter-next-ts-template#4]
When I install the template and run it, I get this error repeating.
 
 Everything works though. What am I doing wrong?
 
 
 ⚠ ./node_modules/@sidan-lab/sidan-csl-rs-browser/sidan_csl_rs_bg.wasm
The generated code contains 'async/await' because this module is using "asyncWebAssembly".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.

Import trace for requested module:
./node_modules/@sidan-lab/sidan-csl-rs-browser/sidan_csl_rs_bg.wasm
./node_modules/@sidan-lab/sidan-csl-rs-browser/sidan_csl_rs.js
./node_modules/@meshsdk/core-csl/dist/index.js
./node_modules/@meshsdk/wallet/dist/index.js
./node_modules/@meshsdk/react/dist/index.js

**Comment by jinglescode** [comment]
its just warnings, nothing to worry about. when we switch to core-cst, these warnings wont be there anymore.
